### PR TITLE
fix input enter (fix #2)

### LINKED ISSUE #2: Add "Enter" support
Right now when I finish typing my to-do item and click the "Enter" button on a keyboard, nothing happens. It should behave the same way as clicking "Добавить".

### PR DESCRIPTION
**Pull request by Bumba-vumba**

### CODE REVIEW

File: project.js [hunk 1]
```diff
@@ -18,4 +19,9 @@ function CreateElement()
 	butt.setAttribute('align', 'center');
 	document.body.appendChild(butt);
 	
+}
+
+document.getElementById('kk').onkeypress = function Enterpush()
+{
+	if (event.keyCode == 13) CreateElement()
```
Comment (MaximAbramchuck) [inline project.js]: Please use triple equals instead of double ones.

https://codeburst.io/javascript-double-equals-vs-triple-equals-61d4ce5a121a

File: project.js [hunk 2]
```diff
@@ -18,4 +19,9 @@ function CreateElement()
 	butt.setAttribute('align', 'center');
 	document.body.appendChild(butt);
 	
+}
+
+document.getElementById('kk').onkeypress = function Enterpush()
```
Comment (MaximAbramchuck) [inline project.js]: No need to name a function, you can make it anonymous.
